services:
  postgres:
    container_name: smart-finance-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=smart_finance

  redis:
    container_name: smart-finance-redis
    image: redis
    ports:
      - 6379:6379