name: valora

services:
  postgres:
    container_name: postgresql
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=valora

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
